labels_file: labels
max_images: 100
model_name: ViT-L-14
root: /home/cdc/Storage/projects/photo-tagger/tests/images
run_dir: runs
thumb_cache: thumb_cache
topk: 7
features:
  llm_enhancer: false
index:
  include_ext:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".dng"
    - ".cr2"
    - ".cr3"
    - ".nef"
    - ".arw"
    - ".rw2"
    - ".orf"
thumbnails:
  xmp_processing: true
  xmp_cache_dir: "xmp_cache"
